import { version } from '../package.json';

export default name =>
  JSON.stringify(
    {
      name: `themer-${name}-ui`,
      theme: 'ui',
      version,
      description: 'Personalized Atom UI theme, generated by themer.',
      keywords: ['themer', 'ui', 'theme'],
      engines: {
        atom: '>=1.0.0 <2.0.0',
      },
    },
    null,
    2
  );
