export default name =>
  JSON.stringify(
    {
      name: `themer-atom-ui-${name}`,
      theme: 'ui',
      version: '0.0.0',
      description: 'Personalized Atom UI theme, generated by themer.',
      keywords: ['themer', 'ui', 'theme'],
      engines: {
        atom: '>=1.0.0 <2.0.0',
      },
    },
    null,
    2
  );
